apiVersion: v1
kind: Service
metadata:
  name: apipersona-service
  namespace: name2  
spec:
  selector:
    app: apipersona-pod      
  ports:
    - protocol: TCP
      port: 80                
      targetPort: 8080        
  type: LoadBalancer  