apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-persona-deployment
  namespace: name1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-persona-pod
  template:
    metadata:
      labels:
        app: api-persona-pod
    spec:
      containers:
        - name: api-container
          image: georgevillanew/api-persona-v2:1.0.0
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: configmap-api-persona