apiVersion: v1
kind: Service
metadata:
  name: service-api-persona
  namespace: name1  
spec:
  selector:
    app: api-persona-pod      
  ports:
    - protocol: TCP
      port: 80                
      targetPort: 8080        
  type: ClusterIP  