apiVersion: v1
kind: Service
metadata:
  name: bdd-apipersona-service
  namespace: name1  
spec:
  selector:
    app: bdd-api-persona-pod       
  ports:
    - protocol: TCP
      port: 3306                
      targetPort: 3306        
  type: ClusterIP  